### API USUARIO - GET
GET http://localhost:8080/api/v1/usuario

### API USUARIO - POST
POST http://localhost:8080/api/v1/usuario
Content-Type: application/json

{
    "id": 0,
    "nome": "lua",
    "email": "lua@123",
    "endereco": "rua abc",
    "telefone": "3344-8876",
    "dataNascimento": "2025-04-15"
}

{
    "id": 0,
    "nome": "luluzinha",
    "email": "luluzinha@321",
    "endereco": "rua dbv",
    "telefone": "9999-5567",
    "dataNascimento": "2025-04-15"
}

### API USUARIO - PUT PUT http://localhost:8080/api/v1/usuario/1 Content-Type: application/json

{
"nome": "maria da silva",
"email": "mari.com.br", 
"endereco": "rua lalalalalla 100", 
"telefone": "5555-1234",
"dataNascimento": "2025-04-15"
}

### API USUARIO - DELETE DELETE http://localhost:8080/api/v1/usuario/1 Content-Type: application/json